import type { Metadata } from "next";
import { Inter, Instrument_Serif } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400"],
});

const fontsClassName = [inter, instrumentSerif]
  .map((font) => font.variable)
  .join(" ");

export const metadata: Metadata = {
  title: "Oceans of Andromeda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontsClassName} antialiased`}>{children}</body>
    </html>
  );
}
